### ISSUE TITLE
Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by palmerj** [blacha/cogeotiff#376]
Get the following error when opening a simple geotiff.

```
$ cogeotiff info -f tests/data/32x32_LZW.TIF
[2020-05-04T03:10:50.568Z] FATAL Failed to run error={ message=Cannot read property 'open' of undefined, stack=TypeError: Cannot read property 'open' of undefined
    at CogSourceFile.fetchBytes (/usr/local/lib/node_modules/@cogeotiff/cli/node_modules/@cogeotiff/source-file/src/cog.source.file.ts:49:26)
    at Fetchable.CogChunk.fetchable.util_fetchable_1.Fetchable [as fetchFunc] (/usr/local/lib/node_modules/@cogeotiff/cli/node_modules/@cogeotiff/core/src/source/cog.chunk.ts:33:46)
    at _valuePromise.Promise (/usr/local/lib/node_modules/@cogeotiff/cli/node_modules/@cogeotiff/core/src/util/util.fetchable.ts:49:46)
    at new Promise (<anonymous>)
    at Fetchable.fetch (/usr/local/lib/node_modules/@cogeotiff/cli/node_modules/@cogeotiff/core/src/util/util.fetchable.ts:47:34)
    at CogChunk.fetch (/usr/local/lib/node_modules/@cogeotiff/cli/node_modules/@cogeotiff/core/src/source/cog.chunk.ts:52:31)
    at CogSourceFile.loadBytes (/usr/local/lib/node_modules/@cogeotiff/cli/node_modules/@cogeotiff/core/src/source/cog.source.ts:262:33)
    at CogTiff.init (/usr/local/lib/node_modules/@cogeotiff/cli/node_modules/@cogeotiff/core/src/cog.tiff.ts:31:27)
    at Object.getCogSource (/usr/local/lib/node_modules/@cogeotiff/cli/src/action.util.ts:36:19)
    at ActionCogInfo.onExecute (/usr/local/lib/node_modules/@cogeotiff/cli/src/action.info.ts:30:42) }
```

OS: Ubuntu 18.04
Node version: v8.10.0

**Comment by blacha** [comment]
This package requires node >=12, I suggest using [n](https://github.com/tj/n) to manage nodejs versions

This error is caused by the nodejs package `fs` not having `fs.promises` which i believe was introduced in node10

**Comment by palmerj** [comment]
Ok upgrading to v12 fixed the issue. Thanks!
